import 'package:flutter/material.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

enum SahIconName {
  mail,
  lock,
  user,
  eye,
  eyeOff,
  arrow,
  arrowLeft,
  chevron,
  chevronRight,
  alert,
  check,
  close,
  search,
  plus,
  edit,
  trash,
  users,
  home,
  chart,
  flame,
  grid,
  list,
  bell,
  settings,
  logout,
  filter,
  download,
  block,
  unblock,
  calendar,
  book,
  moon,
  dumbbell,
  sparkle,
  logs,
  menu,
}

IconData sahIconData(SahIconName name) {
  return switch (name) {
    SahIconName.mail => PhosphorIconsRegular.envelope,
    SahIconName.lock => PhosphorIconsRegular.lock,
    SahIconName.user => PhosphorIconsRegular.user,
    SahIconName.eye => PhosphorIconsRegular.eye,
    SahIconName.eyeOff => PhosphorIconsRegular.eyeSlash,
    SahIconName.arrow => PhosphorIconsRegular.arrowRight,
    SahIconName.arrowLeft => PhosphorIconsRegular.arrowLeft,
    SahIconName.chevron => PhosphorIconsRegular.caretDown,
    SahIconName.chevronRight => PhosphorIconsRegular.caretRight,
    SahIconName.alert => PhosphorIconsRegular.warningCircle,
    SahIconName.check => PhosphorIconsRegular.check,
    SahIconName.close => PhosphorIconsRegular.x,
    SahIconName.search => PhosphorIconsRegular.magnifyingGlass,
    SahIconName.plus => PhosphorIconsRegular.plus,
    SahIconName.edit => PhosphorIconsRegular.pencilSimple,
    SahIconName.trash => PhosphorIconsRegular.trash,
    SahIconName.users => PhosphorIconsRegular.usersThree,
    SahIconName.home => PhosphorIconsRegular.house,
    SahIconName.chart => PhosphorIconsRegular.chartBar,
    SahIconName.flame => PhosphorIconsRegular.flame,
    SahIconName.grid => PhosphorIconsRegular.squaresFour,
    SahIconName.list => PhosphorIconsRegular.list,
    SahIconName.bell => PhosphorIconsRegular.bell,
    SahIconName.settings => PhosphorIconsRegular.gear,
    SahIconName.logout => PhosphorIconsRegular.signOut,
    SahIconName.filter => PhosphorIconsRegular.funnel,
    SahIconName.download => PhosphorIconsRegular.downloadSimple,
    SahIconName.block => PhosphorIconsRegular.prohibit,
    SahIconName.unblock => PhosphorIconsRegular.checkCircle,
    SahIconName.calendar => PhosphorIconsRegular.calendar,
    SahIconName.book => PhosphorIconsRegular.book,
    SahIconName.moon => PhosphorIconsRegular.moon,
    SahIconName.dumbbell => PhosphorIconsRegular.barbell,
    SahIconName.sparkle => PhosphorIconsRegular.sparkle,
    SahIconName.logs => PhosphorIconsRegular.fileText,
    SahIconName.menu => PhosphorIconsRegular.list,
  };
}
